# Generated by Django 5.1.15 on 2026-06-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_integrationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CLOUDINARY', 'Cloudinary')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderrefund',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
