# Generated by Django 5.1.15 on 2026-07-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_order_detail_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsrevision',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='enquiryreply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='faqcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integrationconfig',
            name='integration',
            field=models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('CLOUDINARY', 'Cloudinary'), ('EMAIL', 'Email (SMTP)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='orderevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='policy',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='policy',
            name='og_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('ABOUT_US', 'About Us'), ('TERMS', 'Terms & Conditions'), ('PRIVACY', 'Privacy Policy'), ('SHIPPING', 'Shipping Policy'), ('RETURNS', 'Return & Refund Policy'), ('CONTACT', 'Contact Us')], max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
