# Generated by Django 5.1.15 on 2026-07-12 05:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_cmsrevision_id_alter_enquiryreply_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPendingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=64, unique=True)),
                ('razorpay_order_id', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='PENDING', max_length=12)),
                ('sub_total', models.FloatField()),
                ('coupon_discount', models.FloatField(default=0)),
                ('shipping_amount', models.FloatField(default=0)),
                ('grand_total', models.FloatField()),
                ('shipping_address', models.TextField()),
                ('cart_snapshot', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_rzp_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'razorpay_pending_orders',
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_order_id', models.CharField(max_length=120)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=12)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
                ('pending_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='store.razorpaypendingorder')),
            ],
            options={
                'db_table': 'payment_attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
