# Generated by Django 5.1.15 on 2026-07-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_payment_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='INR — Indian Rupee (₹)', max_length=50),
        ),
    ]
