# Generated by Django 5.1.15 on 2026-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_activitylog_id_alter_customernote_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
